<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/functions.php';require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();$action=(string)($_POST['action']??'');
    try{
        if($action==='zone_save'){
            $district=mb_substr(trim((string)($_POST['district']??'')),0,100);$fee=round((float)($_POST['fee']??0),2);$minutes=max(5,min(600,(int)($_POST['minutes']??45)));$active=isset($_POST['active'])?1:0;
            if($district===''||$fee<0)throw new RuntimeException('Revisa los datos de la zona.');
            db()->prepare('INSERT INTO delivery_zones(district,delivery_fee,estimated_minutes,active) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE delivery_fee=VALUES(delivery_fee),estimated_minutes=VALUES(estimated_minutes),active=VALUES(active)')->execute([$district,$fee,$minutes,$active]);flash('success','Zona guardada.');
        }elseif($action==='coupon_save'){
            $code=strtoupper(preg_replace('/[^A-Z0-9_-]/','',(string)($_POST['code']??'')));$description=mb_substr(trim((string)($_POST['description']??'')),0,160);$type=(string)($_POST['type']??'percent');$value=round((float)($_POST['value']??0),2);$minimum=round((float)($_POST['minimum']??0),2);$maxUses=trim((string)($_POST['max_uses']??''));
            if($code===''||!in_array($type,['percent','fixed'],true)||$value<=0||($type==='percent'&&$value>100))throw new RuntimeException('Revisa el código y el descuento.');
            db()->prepare('INSERT INTO coupons(code,description,discount_type,discount_value,minimum_amount,max_uses,active) VALUES(?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE description=VALUES(description),discount_type=VALUES(discount_type),discount_value=VALUES(discount_value),minimum_amount=VALUES(minimum_amount),max_uses=VALUES(max_uses),active=1')->execute([$code,$description,$type,$value,$minimum,$maxUses===''?null:max(1,(int)$maxUses)]);flash('success','Cupón guardado.');
        }elseif($action==='user_add'){
            $name=mb_substr(trim((string)($_POST['name']??'')),0,100);$username=mb_substr(trim((string)($_POST['username']??'')),0,80);$password=(string)($_POST['password']??'');$role=(string)($_POST['role']??'');
            if(mb_strlen($name)<3||!preg_match('/^[a-zA-Z0-9._-]{3,80}$/D',$username)||strlen($password)<8||!in_array($role,['admin','inventario','caja','atencion'],true))throw new RuntimeException('Completa correctamente el usuario, contraseña y rol.');
            db()->prepare('INSERT INTO users(name,username,password,role) VALUES(?,?,?,?)')->execute([$name,$username,password_hash($password,PASSWORD_DEFAULT),$role]);flash('success','Usuario del equipo creado.');
        }elseif($action==='coupon_toggle'){
            db()->prepare('UPDATE coupons SET active=IF(active=1,0,1) WHERE id=?')->execute([(int)($_POST['id']??0)]);flash('success','Estado del cupón actualizado.');
        }
    }catch(Throwable $exception){flash('danger',$exception instanceof RuntimeException?$exception->getMessage():'No se pudo guardar. Puede existir un registro con el mismo nombre.');}
    redirect('admin/comercial.php');
}
$zones=db()->query('SELECT * FROM delivery_zones ORDER BY delivery_fee,district')->fetchAll();$coupons=db()->query('SELECT * FROM coupons ORDER BY id DESC')->fetchAll();$users=db()->query('SELECT id,name,username,role,created_at FROM users ORDER BY id')->fetchAll();
$pageTitle='Configuración comercial';$pageSubtitle='Zonas de entrega, cupones y permisos del equipo';$activePage='commercial';require __DIR__.'/../includes/admin_header.php';
?>
<section class="admin-suite-grid">
<article class="panel"><div class="panel-heading"><div><h2>Zonas de entrega</h2><p>Configura costo y tiempo estimado.</p></div></div><form method="post" class="admin-inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="zone_save"><input name="district" placeholder="Distrito o recojo" required><input name="fee" type="number" min="0" step="0.10" placeholder="Costo" required><input name="minutes" type="number" min="5" value="45" required><label><input type="checkbox" name="active" checked> Activa</label><button class="btn btn-primary">Guardar</button></form><div class="settings-list"><?php foreach($zones as $zone): ?><div><strong><?= e($zone['district']) ?></strong><span><?= money($zone['delivery_fee']) ?> · <?= (int)$zone['estimated_minutes'] ?> min · <?= $zone['active']?'Activa':'Inactiva' ?></span></div><?php endforeach ?></div></article>
<article class="panel"><div class="panel-heading"><div><h2>Cupones</h2><p>Descuentos con límites y monto mínimo.</p></div></div><form method="post" class="admin-inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="coupon_save"><input name="code" placeholder="CÓDIGO" required><input name="description" placeholder="Descripción"><select name="type"><option value="percent">Porcentaje</option><option value="fixed">Monto fijo</option></select><input name="value" type="number" min="0.01" step="0.01" placeholder="Valor" required><input name="minimum" type="number" min="0" step="0.01" placeholder="Compra mínima"><input name="max_uses" type="number" min="1" placeholder="Usos máximos"><button class="btn btn-primary">Guardar</button></form><div class="settings-list"><?php foreach($coupons as $coupon): ?><div><strong><?= e($coupon['code']) ?></strong><span><?= e($coupon['description']) ?> · <?= $coupon['discount_type']==='percent'?e($coupon['discount_value']).'%':money($coupon['discount_value']) ?> · <?= (int)$coupon['used_count'] ?> usos</span><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="coupon_toggle"><input type="hidden" name="id" value="<?= (int)$coupon['id'] ?>"><button><?= $coupon['active']?'Desactivar':'Activar' ?></button></form></div><?php endforeach ?></div></article>
</section>
<section class="panel"><div class="panel-heading"><div><h2>Usuarios y roles</h2><p>Crea accesos separados para inventario, caja y atención.</p></div></div><form method="post" class="admin-inline-form"><?= csrf_field() ?><input type="hidden" name="action" value="user_add"><input name="name" placeholder="Nombre" required><input name="username" placeholder="Usuario" required><input type="password" name="password" minlength="8" placeholder="Contraseña" required><select name="role"><option value="inventario">Inventario</option><option value="caja">Caja</option><option value="atencion">Atención</option><option value="admin">Administrador</option></select><button class="btn btn-primary">Crear usuario</button></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Creado</th></tr></thead><tbody><?php foreach($users as $user): ?><tr><td><?= e($user['name']) ?></td><td><?= e($user['username']) ?></td><td><?= e(ucfirst($user['role'])) ?></td><td><?= e(date('d/m/Y',strtotime($user['created_at']))) ?></td></tr><?php endforeach ?></tbody></table></div></section>
<?php require __DIR__.'/../includes/admin_footer.php'; ?>

