<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/functions.php';require_admin();
$metrics=db()->query("SELECT COUNT(*) total_orders,COALESCE(SUM(expected_amount),0) revenue,COALESCE(SUM(discount_amount),0) discounts,COALESCE(SUM(delivery_fee),0) delivery_income,COUNT(DISTINCT customer_id) customers FROM yape_orders WHERE status='aprobado'")->fetch();
$customers=(int)db()->query('SELECT COUNT(*) FROM customers WHERE active=1')->fetchColumn();$favorites=(int)db()->query('SELECT COUNT(*) FROM customer_favorites')->fetchColumn();$external=(int)db()->query('SELECT COUNT(*) FROM productos p WHERE activo=1 AND '.safe_external_catalog_condition('p'))->fetchColumn();
$days=db()->query("SELECT DATE(created_at) day,COUNT(*) orders,COALESCE(SUM(expected_amount),0) total FROM yape_orders WHERE status='aprobado' AND created_at>=DATE_SUB(CURDATE(),INTERVAL 13 DAY) GROUP BY DATE(created_at) ORDER BY day")->fetchAll();
$top=db()->query("SELECT item_name,SUM(quantity) quantity,SUM(subtotal) total FROM yape_order_items i INNER JOIN yape_orders o ON o.id=i.order_id WHERE o.status='aprobado' GROUP BY item_name ORDER BY quantity DESC LIMIT 10")->fetchAll();
$dayTotals=array_map(static fn($row)=>(float)$row['total'],$days);
$maxDay=$dayTotals?max(1,max($dayTotals)):1;
$pageTitle='Estadísticas';$pageSubtitle='Ventas, clientes, productos y comportamiento';$activePage='statistics';require __DIR__.'/../includes/admin_header.php';
?>
<section class="metric-grid metric-grid-five"><article class="metric-card metric-green"><div><span>Ventas aprobadas</span><strong><?= money($metrics['revenue']) ?></strong><small><?= (int)$metrics['total_orders'] ?> pedidos</small></div></article><article class="metric-card metric-blue"><div><span>Clientes registrados</span><strong><?= number_format($customers) ?></strong><small><?= (int)$metrics['customers'] ?> compraron</small></div></article><article class="metric-card metric-purple"><div><span>Catálogo externo</span><strong><?= number_format($external) ?></strong><small>Productos disponibles</small></div></article><article class="metric-card metric-orange"><div><span>Descuentos</span><strong><?= money($metrics['discounts']) ?></strong><small>Cupones aplicados</small></div></article><article class="metric-card metric-pink"><div><span>Favoritos</span><strong><?= number_format($favorites) ?></strong><small>Productos guardados</small></div></article></section>
<section class="dashboard-grid"><article class="panel"><div class="panel-heading"><div><h2>Ventas de los últimos 14 días</h2><p>Pedidos aprobados por fecha.</p></div></div><div class="sales-bars"><?php foreach($days as $day): ?><div><span><?= e(date('d/m',strtotime($day['day']))) ?></span><i style="height:<?= number_format(((float)$day['total']/$maxDay)*160,0) ?>px"></i><strong><?= money($day['total']) ?></strong></div><?php endforeach ?><?php if(!$days): ?><p>Aún no existen ventas aprobadas.</p><?php endif ?></div></article><article class="panel"><div class="panel-heading"><div><h2>Productos más vendidos</h2><p>Cantidad e ingreso acumulado.</p></div></div><div class="settings-list"><?php foreach($top as $item): ?><div><strong><?= e($item['item_name']) ?></strong><span><?= (int)$item['quantity'] ?> unidades · <?= money($item['total']) ?></span></div><?php endforeach ?><?php if(!$top): ?><p>Aún no hay información de ventas.</p><?php endif ?></div></article></section>
<?php require __DIR__.'/../includes/admin_footer.php'; ?>
